### ISSUE TITLE
这个项目怎么导入部署？能不能出个教程谢谢了

### ISSUE THREAD

**Issue by hubspring** [29DCH/Online-learning-cloud-platform#1]

**Comment by kaitai2018** [comment]
怎么运行起来的，关注。要不开源没什么作用

**Comment by 29DCH** [comment]
配置文档内容有点多,当时就没写了,就写了技术点,功能点相关的文档
这个项目我当时上传的时候缺了点东西,所以如果感兴趣的话建议你还是自己重新构建吧,我的仅供参考




------------------ 原始邮件 ------------------
发件人: "MingHanYan"<notifications@github.com>;
发送时间: 2019年4月22日(星期一) 下午5:25
收件人: "29DCH/Online-learning-cloud-platform"<Online-learning-cloud-platform@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [29DCH/Online-learning-cloud-platform] 这个项目怎么导入部署？能不能出个教程谢谢了 (#1)




怎么运行起来的，关注。要不开源没什么作用
